function out1 = subs_x(alpha,beta,gamma)
%SUBS_X
%    OUT1 = SUBS_X(ALPHA,BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    28-Jun-2018 00:22:11

t2 = cos(beta);
t3 = sin(beta);
t4 = cos(alpha);
t5 = sin(alpha);
t6 = sin(gamma);
t7 = cos(gamma);
out1 = [t3.*(-1.0./1.0e1);t2.*t5.*(1.0./1.0e1);t2.*t4.*(-1.0./1.0e1);t3.*(t6.*2.0-3.0).*(1.0./1.0e1);t2.*t5.*(3.0./1.0e1)+t4.*t7.*(1.0./5.0)-t2.*t5.*t6.*(1.0./5.0);t2.*t4.*(-3.0./1.0e1)+t5.*t7.*(1.0./5.0)+t2.*t4.*t6.*(1.0./5.0)];
