function out1 = subs_xdd(alpha,beta,gamma,alpha_d,beta_d,gamma_d,alpha_dd,beta_dd,gamma_dd)
%SUBS_XDD
%    OUT1 = SUBS_XDD(ALPHA,BETA,GAMMA,ALPHA_D,BETA_D,GAMMA_D,ALPHA_DD,BETA_DD,GAMMA_DD)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    26-Jun-2018 20:58:20

t2 = cos(beta);
t3 = sin(beta);
t4 = cos(alpha);
t5 = sin(alpha);
t6 = cos(gamma);
t7 = sin(gamma);
t8 = t7.*2.0;
t9 = t8-3.0;
t10 = t4.*t6.*(1.0./5.0);
t11 = t5.*t7.*(1.0./5.0);
t21 = t2.*t4.*t6.*(1.0./5.0);
t12 = t11-t21;
t13 = t4.*t7.*(1.0./5.0);
t14 = t2.*t5.*t6.*(1.0./5.0);
t15 = t13+t14;
t16 = t5.*t6.*(1.0./5.0);
t17 = t2.*t4.*t7.*(1.0./5.0);
t18 = t2.*t5.*(3.0./1.0e1);
t19 = t10+t18-t2.*t5.*t7.*(1.0./5.0);
t20 = t16+t17-t2.*t4.*(3.0./1.0e1);
out1 = [beta_dd.*(t2-beta_d.*t3).*(-1.0./1.0e1);-alpha_dd.*(alpha_d.*t2.*t5.*(1.0./1.0e1)+beta_d.*t3.*t4.*(1.0./1.0e1))-beta_dd.*(alpha_d.*t3.*t4.*(1.0./1.0e1)+beta_d.*t2.*t5.*(1.0./1.0e1))+alpha_dd.*t2.*t4.*(1.0./1.0e1)-beta_dd.*t3.*t5.*(1.0./1.0e1);alpha_dd.*(alpha_d.*t2.*t4.*(1.0./1.0e1)-beta_d.*t3.*t5.*(1.0./1.0e1))-beta_dd.*(alpha_d.*t3.*t5.*(1.0./1.0e1)-beta_d.*t2.*t4.*(1.0./1.0e1))+alpha_dd.*t2.*t5.*(1.0./1.0e1)+beta_dd.*t3.*t4.*(1.0./1.0e1);-beta_dd.*(beta_d.*t3.*t9.*(1.0./1.0e1)-gamma_d.*t2.*t6.*(1.0./5.0))+gamma_dd.*(beta_d.*t2.*t6.*(1.0./5.0)-gamma_d.*t3.*t7.*(1.0./5.0))+beta_dd.*t2.*t9.*(1.0./1.0e1)+gamma_dd.*t3.*t6.*(1.0./5.0);-alpha_dd.*t20-gamma_dd.*t15+beta_dd.*(alpha_d.*t3.*t4.*t9.*(1.0./1.0e1)+beta_d.*t2.*t5.*t9.*(1.0./1.0e1)+gamma_d.*t3.*t5.*t6.*(1.0./5.0))+alpha_dd.*(-alpha_d.*t19+gamma_d.*t12+beta_d.*t3.*t4.*t9.*(1.0./1.0e1))+gamma_dd.*(alpha_d.*t12-gamma_d.*(t10-t2.*t5.*t7.*(1.0./5.0))+beta_d.*t3.*t5.*t6.*(1.0./5.0))+beta_dd.*t3.*t5.*t9.*(1.0./1.0e1);alpha_dd.*t19-gamma_dd.*t12-beta_dd.*(alpha_d.*t3.*t5.*t9.*(-1.0./1.0e1)+beta_d.*t2.*t4.*t9.*(1.0./1.0e1)+gamma_d.*t3.*t4.*t6.*(1.0./5.0))-gamma_dd.*(gamma_d.*(t16+t17)+alpha_d.*t15+beta_d.*t3.*t4.*t6.*(1.0./5.0))-alpha_dd.*(alpha_d.*t20+gamma_d.*t15-beta_d.*t3.*t5.*t9.*(1.0./1.0e1))-beta_dd.*t3.*t4.*t9.*(1.0./1.0e1)];
