function out1 = subs_x_full(alpha,beta,gamma)
%SUBS_X_FULL
%    OUT1 = SUBS_X_FULL(ALPHA,BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2018 09:01:32

t2 = cos(beta);
t3 = sin(beta);
t4 = cos(alpha);
t5 = sin(alpha);
t6 = sin(gamma);
t7 = cos(gamma);
t8 = t2.*t5.*(3.0./1.0e1);
t9 = t2.*t4.*(3.0./1.0e1);
out1 = [t3.*(-1.0./1.0e1);t2.*t5.*(1.0./1.0e1);t2.*t4.*(-1.0./1.0e1);t3.*(t6.*2.0-3.0).*(1.0./1.0e1);t8+t4.*t7.*(1.0./5.0)-t2.*t5.*t6.*(1.0./5.0);t2.*t4.*(-3.0./1.0e1)+t5.*t7.*(1.0./5.0)+t2.*t4.*t6.*(1.0./5.0);t3.*(3.0./1.0e1);-t8;t9;t3.*(t6.*4.0+3.0).*(1.0./1.0e1);-t8+t4.*t7.*(2.0./5.0)-t2.*t5.*t6.*(2.0./5.0);t9+t5.*t7.*(2.0./5.0)+t2.*t4.*t6.*(2.0./5.0)];
