function out1 = subs_torque(alpha,beta,gamma,alpha_d,beta_d,gamma_d)
%SUBS_TORQUE
%    OUT1 = SUBS_TORQUE(ALPHA,BETA,GAMMA,ALPHA_D,BETA_D,GAMMA_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    26-Jun-2018 20:58:05

t2 = cos(beta);
t3 = cos(gamma);
t4 = sin(alpha);
t5 = beta_d.^2;
t6 = sin(gamma);
t7 = sin(beta);
t8 = t3.^2;
t9 = t2.^2;
t10 = beta.*2.0;
t11 = sin(t10);
t12 = cos(alpha);
t13 = gamma.*2.0;
t14 = sin(t13);
t15 = alpha_d.^2;
out1 = [t2.*t4.*(-1.1772e1)-t3.*t12.*5.886+gamma_d.^2.*t2.*t3.*(9.0./5.0e1)+alpha_d.*beta_d.*t11.*(2.1e1./5.0e1)+alpha_d.*gamma_d.*t14.*(3.0./2.5e1)-t2.*t3.*t5.*(9.0./5.0e1)+t2.*t4.*t6.*5.886+alpha_d.*gamma_d.*t3.*t9.*(9.0./2.5e1)+beta_d.*gamma_d.*t7.*t8.*(6.0./2.5e1)+t2.*t3.*t5.*t6.*(3.0./2.5e1)-alpha_d.*beta_d.*t2.*t6.*t7.*(1.8e1./2.5e1)-alpha_d.*beta_d.*t2.*t7.*t8.*(6.0./2.5e1)-alpha_d.*gamma_d.*t3.*t6.*t9.*(6.0./2.5e1);t7.*t12.*(-1.1772e1)-t11.*t15.*(2.1e1./1.0e2)-alpha_d.*gamma_d.*t7.*(6.0./2.5e1)+beta_d.*gamma_d.*t3.*(9.0./2.5e1)-beta_d.*gamma_d.*t14.*(3.0./2.5e1)+t6.*t7.*t12.*5.886+alpha_d.*gamma_d.*t6.*t7.*(9.0./2.5e1)+alpha_d.*gamma_d.*t7.*t8.*(6.0./2.5e1)+t2.*t6.*t7.*t15.*(9.0./2.5e1)+t2.*t7.*t8.*t15.*(3.0./2.5e1);t3.*t5.*(-9.0./5.0e1)+t4.*t6.*5.886+t5.*t14.*(3.0./5.0e1)-t14.*t15.*(3.0./5.0e1)+alpha_d.*beta_d.*t7.*(6.0./2.5e1)-t2.*t3.*t12.*5.886-t3.*t9.*t15.*(9.0./5.0e1)-alpha_d.*beta_d.*t6.*t7.*(9.0./2.5e1)-alpha_d.*beta_d.*t7.*t8.*(6.0./2.5e1)+t3.*t6.*t9.*t15.*(3.0./2.5e1)];
