function D = subs_D(q0,q1,q2,q3,x,y,z,x_d,y_d,z_d)
%SUBS_D
%    D = SUBS_D(Q0,Q1,Q2,Q3,X,Y,Z,X_D,Y_D,Z_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Jun-2018 18:58:59

t2 = abs(x_d);
t3 = abs(y_d);
t4 = abs(z_d);
t5 = t2.^2;
t6 = t3.^2;
t7 = t4.^2;
t8 = t5+t6+t7;
t9 = sqrt(t8);
D = [t9.*x_d.*pi.*(-5.0./1.6e1);t9.*y_d.*pi.*(-5.0./1.6e1);t9.*z_d.*pi.*(-5.0./1.6e1)];
