function Dd = subs_Dd(q0,q1,q2,q3)
%SUBS_DD
%    DD = SUBS_DD(Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    22-Jun-2018 10:59:45

Dd = [0.0,0.0,0.0,q0.*2.0,q1.*2.0,q2.*2.0,q3.*2.0,0.0,0.0,0.0,0.0,0.0,0.0];
