function X_state = subs_X_state(x,y,z,q0,q1,q2,q3,x_d,y_d,z_d,omega_x,omega_y,omega_z)
%SUBS_X_STATE
%    X_STATE = SUBS_X_STATE(X,Y,Z,Q0,Q1,Q2,Q3,X_D,Y_D,Z_D,OMEGA_X,OMEGA_Y,OMEGA_Z)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    22-Jun-2018 11:00:42

X_state = [x;y;z;q0;q1;q2;q3;x_d;y_d;z_d;omega_x;omega_y;omega_z];
