function out1 = subs_x(phi2,phi4,phi5)
%SUBS_X
%    OUT1 = SUBS_X(PHI2,PHI4,PHI5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Jun-2018 11:44:16

t2 = cos(phi4);
t3 = sin(phi4);
t4 = t2.*(7.0./1.0e1);
t5 = cos(phi5);
out1 = [phi2;cos(phi2).*(1.0./5.0);sin(phi2).*(1.0./5.0)+3.0./1.0e1;phi4;t2.*(2.0./5.0);t3.*(2.0./5.0);phi4;t4+t5.*(3.0./1.0e1);t3.*(7.0./1.0e1)+sin(phi5).*(3.0./1.0e1);phi5;t4+t5.*(3.0./5.0)];
