function out1 = subs_Cd(phi2,phi4,phi5)
%SUBS_CD
%    OUT1 = SUBS_CD(PHI2,PHI4,PHI5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Jun-2018 15:51:17

out1 = reshape([sin(phi2).*(-1.0./5.0),0.0,sqrt(1.3e1).*sin(phi4).*(-1.0./1.0e1),cos(phi4).*(7.0./1.0e1),0.0,cos(phi5).*(3.0./5.0)],[2,3]);
