function sigma_a = subs_F_drag(x_d,y_d,z_d)
%SUBS_F_DRAG
%    SIGMA_A = SUBS_F_DRAG(X_D,Y_D,Z_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    14-Jun-2018 12:02:06

t2 = x_d.^2;
t3 = y_d.^2;
t4 = z_d.^2;
t5 = t2+t3+t4;
t6 = sqrt(t5);
sigma_a = [t6.*x_d.*pi.*(5.0./1.6e1);t6.*y_d.*pi.*(5.0./1.6e1);t6.*z_d.*pi.*(5.0./1.6e1)];
