function D = subs_D(q0,q1,q2,q3)
%SUBS_D
%    D = SUBS_D(Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    14-Jun-2018 12:02:05

D = q0.^2+q1.^2+q2.^2+q3.^2-1.0;
