function out1 = subs_C(x1,y1,phi1,x2,y2,phi2)
%SUBS_C
%    OUT1 = SUBS_C(X1,Y1,PHI1,X2,Y2,PHI2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Jun-2018 15:22:19

out1 = [x1-x2+cos(phi1).*(1.0./2.0)+cos(phi2).*(1.0./8.0);y1-y2+sin(phi1).*(1.0./2.0)+sin(phi2).*(1.0./8.0)];
