function out1 = subs_Dd(phi1,phi2)
%SUBS_DD
%    OUT1 = SUBS_DD(PHI1,PHI2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Jun-2018 15:22:20

out1 = reshape([-sin(phi1),0.0,cos(phi1),0.0,-1.0./2.0,0.0,0.0,-sin(phi2),0.0,cos(phi2),0.0,1.0./8.0],[2,6]);
